
import java.awt.*;
import java.util.*;
import javax.swing.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;
import pack.DBLoader;

public class editproductdata extends javax.swing.JFrame {

    File file;

    editproductdata(String pid, String pname, String cat, String des, String barcode, String price, String photo) {
        initComponents();
        setSize(800, 900);
        setTitle("Edit Products");
        getContentPane().setBackground(new java.awt.Color(204, 204, 255));
        getcategories();
        tfpid.setEnabled(false);
        tfpid.setText(pid);
        tfbarcode.setText(barcode);
        tfdes.setText(des);
        tfpname.setText(pname);
        tfprice.setText(price);
        jComboBox1.setSelectedItem(cat);
        ImageIcon icon = new ImageIcon(photo);
        Image img = icon.getImage();
        Image newimg = img.getScaledInstance(lbpreview.getWidth(), lbpreview.getHeight(), Image.SCALE_SMOOTH);
        lbpreview.setIcon(new ImageIcon(newimg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfpname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfdes = new javax.swing.JTextArea();
        tfprice = new javax.swing.JTextField();
        tfbarcode = new javax.swing.JTextField();
        lbpreview = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfpid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Products");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 490, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Category");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 170, 40);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 130, 280, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Product Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 170, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Description");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 150, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 320, 150, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Barcode");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 370, 150, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Photo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 440, 150, 40);
        getContentPane().add(tfpname);
        tfpname.setBounds(240, 190, 280, 40);

        tfdes.setColumns(20);
        tfdes.setRows(5);
        jScrollPane1.setViewportView(tfdes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 240, 280, 70);
        getContentPane().add(tfprice);
        tfprice.setBounds(240, 320, 280, 40);
        getContentPane().add(tfbarcode);
        tfbarcode.setBounds(240, 370, 280, 40);

        lbpreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbpreview);
        lbpreview.setBounds(240, 430, 150, 130);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 469, 120, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 600, 140, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Product id");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 90, 110, 30);
        getContentPane().add(tfpid);
        tfpid.setBounds(240, 90, 280, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jfc = new JFileChooser("C:\\");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpeg", "jpg", "bmp", "png", "jfif");
        jfc.setFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        int returnVal = jfc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            try {
                BufferedImage img = ImageIO.read(file);
                BufferedImage newimg = resizephoto(img, lbpreview.getWidth(), lbpreview.getHeight());
                lbpreview.setIcon(new ImageIcon(newimg));
            } catch (Exception ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String pid = tfpid.getText();
            String catname = (String) jComboBox1.getSelectedItem();
            String pname = tfpname.getText();
            String des = tfdes.getText();
            String price = tfprice.getText();
            String barcode = tfbarcode.getText();
            ResultSet rs = DBLoader.executeStatement("select * from products where pid='" + pid + "'");
            if (file == null) {
                rs.next();
                rs.moveToCurrentRow();
                rs.updateString("pname", pname);
                rs.updateString("description", des);
                rs.updateString("barcode", barcode);
                rs.updateString("price", price);
                rs.updateString("category", catname);
                rs.updateRow();
                JOptionPane.showMessageDialog(this, "Product Edited");
            } else {
                String newfilename = new Date().getTime() + ".jpg";
                new savefileinfolder(file, newfilename);
                rs.next();
                rs.moveToCurrentRow();
                rs.updateString("pname", pname);
                rs.updateString("description", des);
                rs.updateString("barcode", barcode);
                rs.updateString("price", price);
                rs.updateString("catname", catname);
                rs.updateString("photo", "src/uploaded_pics/" + newfilename);
                rs.updateRow();
                JOptionPane.showMessageDialog(this, "Product Edited");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbpreview;
    private javax.swing.JTextField tfbarcode;
    private javax.swing.JTextArea tfdes;
    private javax.swing.JTextField tfpid;
    private javax.swing.JTextField tfpname;
    private javax.swing.JTextField tfprice;
    // End of variables declaration//GEN-END:variables
 BufferedImage resizephoto(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

    private void getcategories() {
        try {
            ResultSet rs = DBLoader.executeStatement("select * from categories");
            while (rs.next()) {
                String catname = rs.getString("catname");
                jComboBox1.addItem(catname);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}